# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bfs.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BFS(object):
    def setupUi(self, BFS):
        BFS.setObjectName("BFS")
        BFS.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BFS.setWindowIcon(icon)
        BFS.setStyleSheet("background-color: rgb(211, 233, 235);")
        self.label = QtWidgets.QLabel(BFS)
        self.label.setGeometry(QtCore.QRect(100, 60, 221, 20))
        self.label.setObjectName("label")
        self.bfsrevenir = QtWidgets.QCommandLinkButton(BFS)
        self.bfsrevenir.setGeometry(QtCore.QRect(10, 0, 51, 51))
        self.bfsrevenir.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imgs/iconrevenir.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bfsrevenir.setIcon(icon1)
        self.bfsrevenir.setIconSize(QtCore.QSize(40, 40))
        self.bfsrevenir.setObjectName("bfsrevenir")
        self.tableWidget = QtWidgets.QTableWidget(BFS)
        self.tableWidget.setGeometry(QtCore.QRect(130, 90, 151, 192))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)

        self.retranslateUi(BFS)
        QtCore.QMetaObject.connectSlotsByName(BFS)

    def retranslateUi(self, BFS):
        _translate = QtCore.QCoreApplication.translate
        BFS.setWindowTitle(_translate("BFS", "BFS"))
        self.label.setText(_translate("BFS", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Resultat de l\'algorithme de BFS :</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("BFS", "BFS(sommet)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BFS = QtWidgets.QWidget()
    ui = Ui_BFS()
    ui.setupUi(BFS)
    BFS.show()
    sys.exit(app.exec_())
