# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coût.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cout(object):
    def setupUi(self, cout):
        cout.setObjectName("cout")
        cout.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cout.setWindowIcon(icon)
        cout.setStyleSheet("background-color: rgb(219, 242, 244);")
        self.label = QtWidgets.QLabel(cout)
        self.label.setGeometry(QtCore.QRect(150, 30, 81, 20))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(cout)
        self.tableWidget.setGeometry(QtCore.QRect(50, 50, 291, 211))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.click1cout = QtWidgets.QCommandLinkButton(cout)
        self.click1cout.setGeometry(QtCore.QRect(10, 0, 41, 41))
        self.click1cout.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imgs/iconrevenir.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.click1cout.setIcon(icon1)
        self.click1cout.setIconSize(QtCore.QSize(30, 30))
        self.click1cout.setObjectName("click1cout")
        self.click2cout = QtWidgets.QCommandLinkButton(cout)
        self.click2cout.setGeometry(QtCore.QRect(350, 260, 41, 41))
        self.click2cout.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imgs/iconavant.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.click2cout.setIcon(icon2)
        self.click2cout.setIconSize(QtCore.QSize(30, 30))
        self.click2cout.setObjectName("click2cout")

        self.retranslateUi(cout)
        QtCore.QMetaObject.connectSlotsByName(cout)

    def retranslateUi(self, cout):
        _translate = QtCore.QCoreApplication.translate
        cout.setWindowTitle(_translate("cout", "cout"))
        self.label.setText(_translate("cout", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Les coûts  :</span></p><p><br/></p></body></html>"))
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cout = QtWidgets.QWidget()
    ui = Ui_cout()
    ui.setupUi(cout)
    cout.show()
    sys.exit(app.exec_())
