# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dijikstra.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dijikstra(object):
    def setupUi(self, Dijikstra):
        Dijikstra.setObjectName("Dijikstra")
        Dijikstra.resize(400, 349)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dijikstra.setWindowIcon(icon)
        Dijikstra.setStyleSheet("background-color: rgb(219, 242, 244);")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Dijikstra)
        self.commandLinkButton.setGeometry(QtCore.QRect(10, 0, 41, 41))
        self.commandLinkButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imgs/iconrevenir.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon1)
        self.commandLinkButton.setIconSize(QtCore.QSize(30, 30))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.label = QtWidgets.QLabel(Dijikstra)
        self.label.setGeometry(QtCore.QRect(90, 30, 111, 20))
        self.label.setObjectName("label")
        self.sommet = QtWidgets.QLineEdit(Dijikstra)
        self.sommet.setGeometry(QtCore.QRect(210, 30, 31, 20))
        self.sommet.setObjectName("sommet")
        self.sommetbutton = QtWidgets.QPushButton(Dijikstra)
        self.sommetbutton.setGeometry(QtCore.QRect(290, 30, 75, 23))
        self.sommetbutton.setStyleSheet("background-color: rgb(90, 170, 255);")
        self.sommetbutton.setObjectName("sommetbutton")
        self.tableWidget = QtWidgets.QTableWidget(Dijikstra)
        self.tableWidget.setGeometry(QtCore.QRect(20, 60, 361, 91))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.inter = QtWidgets.QLabel(Dijikstra)
        self.inter.setGeometry(QtCore.QRect(60, 170, 261, 20))
        self.inter.setText("")
        self.inter.setObjectName("inter")
        self.textBrowser = QtWidgets.QTextBrowser(Dijikstra)
        self.textBrowser.setGeometry(QtCore.QRect(70, 200, 256, 131))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dijikstra)
        QtCore.QMetaObject.connectSlotsByName(Dijikstra)

    def retranslateUi(self, Dijikstra):
        _translate = QtCore.QCoreApplication.translate
        Dijikstra.setWindowTitle(_translate("Dijikstra", "Dijikstra"))
        self.label.setText(_translate("Dijikstra", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Sommet Depart :</span></p></body></html>"))
        self.sommetbutton.setText(_translate("Dijikstra", "valider"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dijikstra = QtWidgets.QWidget()
    ui = Ui_Dijikstra()
    ui.setupUi(Dijikstra)
    Dijikstra.show()
    sys.exit(app.exec_())
