# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_page3(object):
    def setupUi(self, page3):
        page3.setObjectName("page3")
        page3.resize(400, 360)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        page3.setWindowIcon(icon)
        page3.setStyleSheet("background-color: rgb(219, 242, 244);")
        self.label = QtWidgets.QLabel(page3)
        self.label.setGeometry(QtCore.QRect(100, 20, 211, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(page3)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 101, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(page3)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(page3)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(page3)
        self.label_5.setGeometry(QtCore.QRect(30, 180, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(page3)
        self.label_6.setGeometry(QtCore.QRect(30, 210, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(page3)
        self.label_7.setGeometry(QtCore.QRect(30, 240, 101, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(page3)
        self.label_8.setGeometry(QtCore.QRect(30, 270, 101, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(page3)
        self.label_9.setGeometry(QtCore.QRect(30, 150, 47, 14))
        self.label_9.setObjectName("label_9")
        self.typegraphe = QtWidgets.QLineEdit(page3)
        self.typegraphe.setGeometry(QtCore.QRect(170, 60, 113, 20))
        self.typegraphe.setObjectName("typegraphe")
        self.ordregraphe = QtWidgets.QLineEdit(page3)
        self.ordregraphe.setGeometry(QtCore.QRect(170, 90, 113, 20))
        self.ordregraphe.setObjectName("ordregraphe")
        self.taillegraphe = QtWidgets.QLineEdit(page3)
        self.taillegraphe.setGeometry(QtCore.QRect(170, 120, 113, 20))
        self.taillegraphe.setObjectName("taillegraphe")
        self.densite = QtWidgets.QLineEdit(page3)
        self.densite.setGeometry(QtCore.QRect(170, 150, 113, 20))
        self.densite.setObjectName("densite")
        self.sommets = QtWidgets.QLineEdit(page3)
        self.sommets.setGeometry(QtCore.QRect(170, 180, 113, 20))
        self.sommets.setObjectName("sommets")
        self.complet = QtWidgets.QLineEdit(page3)
        self.complet.setGeometry(QtCore.QRect(170, 210, 113, 20))
        self.complet.setObjectName("complet")
        self.connexe = QtWidgets.QLineEdit(page3)
        self.connexe.setGeometry(QtCore.QRect(170, 240, 113, 20))
        self.connexe.setObjectName("connexe")
        self.reguliere = QtWidgets.QLineEdit(page3)
        self.reguliere.setGeometry(QtCore.QRect(170, 270, 113, 20))
        self.reguliere.setObjectName("reguliere")
        self.widget = QtWidgets.QWidget(page3)
        self.widget.setGeometry(QtCore.QRect(90, 320, 241, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.algorithmes = QtWidgets.QPushButton(self.widget)
        self.algorithmes.setStyleSheet("background-color: rgb(89, 160, 235);")
        self.algorithmes.setObjectName("algorithmes")
        self.horizontalLayout.addWidget(self.algorithmes)
        self.voirgraphe = QtWidgets.QPushButton(self.widget)
        self.voirgraphe.setStyleSheet("background-color: rgb(96, 173, 255);\n"
"background-color: rgb(84, 151, 223);")
        self.voirgraphe.setObjectName("voirgraphe")
        self.horizontalLayout.addWidget(self.voirgraphe)

        self.retranslateUi(page3)
        QtCore.QMetaObject.connectSlotsByName(page3)

    def retranslateUi(self, page3):
        _translate = QtCore.QCoreApplication.translate
        page3.setWindowTitle(_translate("page3", "Informations du Graphe"))
        self.label.setText(_translate("page3", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Informations du graphe </span></p></body></html>"))
        self.label_2.setText(_translate("page3", "Type du Graphe :"))
        self.label_3.setText(_translate("page3", "Ordre du Graphe :"))
        self.label_4.setText(_translate("page3", "Taille du Graphe :"))
        self.label_5.setText(_translate("page3", "Les sommets :"))
        self.label_6.setText(_translate("page3", "Graphe Complet ? :"))
        self.label_7.setText(_translate("page3", "Graphe Connexe ? :"))
        self.label_8.setText(_translate("page3", "Graphe Réguliere ? :"))
        self.label_9.setText(_translate("page3", "Densité :"))
        self.algorithmes.setText(_translate("page3", "Alogorithmes"))
        self.voirgraphe.setText(_translate("page3", "Voir Graphe"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page3 = QtWidgets.QWidget()
    ui = Ui_page3()
    ui.setupUi(page3)
    page3.show()
    sys.exit(app.exec_())
