# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MatriceAdjacent.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(400, 400)
        Form.setMinimumSize(QtCore.QSize(400, 400))
        Form.setMaximumSize(QtCore.QSize(400, 400))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setWindowOpacity(1.0)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(219, 242, 244);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 40, 171, 20))
        self.label.setObjectName("label")
        self.iconavant = QtWidgets.QCommandLinkButton(Form)
        self.iconavant.setGeometry(QtCore.QRect(340, 350, 51, 41))
        self.iconavant.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imgs/iconavant.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iconavant.setIcon(icon1)
        self.iconavant.setIconSize(QtCore.QSize(30, 30))
        self.iconavant.setObjectName("iconavant")
        self.iconrevenir = QtWidgets.QCommandLinkButton(Form)
        self.iconrevenir.setGeometry(QtCore.QRect(10, 0, 41, 41))
        self.iconrevenir.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.iconrevenir.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imgs/iconrevenir.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iconrevenir.setIcon(icon2)
        self.iconrevenir.setIconSize(QtCore.QSize(30, 30))
        self.iconrevenir.setObjectName("iconrevenir")
        self.matrice = QtWidgets.QTableWidget(Form)
        self.matrice.setGeometry(QtCore.QRect(50, 70, 281, 301))
        self.matrice.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.matrice.setLineWidth(1)
        self.matrice.setObjectName("matrice")
        self.matrice.setColumnCount(0)
        self.matrice.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Matrice D\'adjacent"))
        Form.setAccessibleName(_translate("Form", "bbbbb"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Matrice D\'adjacence :</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
